=== MSCloud2130/Bioway/Diseño/Persistencia/ProductSearch/product_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "Schema usado para la persistencia de los productos en el servicio SOAP",
    "default": {},
    "examples": [
        {
            "_id": "43dcecc9-724c-4062-ac8f-402621f18485",
            "name": "Hotel Santa Marta",
            "type": "ACCOMMODATION",
            "uri": "http://localhost:8080/products/43dcecc9-724c-4062-ac8f-402621f18485",
            "supplierId": "cd96b919-d54d-43ca-b648-b90153def1b2",
            "_class": "com.omega.bioway.ProductSearch.crosscutting.entities.Product"
        }
    ],
    "required": [
        "_id",
        "name",
        "type",
        "uri",
        "supplierId",
        "_class"
    ],
    "properties": {
        "_id": {
            "$id": "#/properties/_id",
            "type": "string",
            "title": "The _id schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "43dcecc9-724c-4062-ac8f-402621f18485"
            ]
        },
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "The name schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "Hotel Santa Marta"
            ]
        },
        "type": {
            "$id": "#/properties/type",
            "type": "string",
            "title": "The type schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "ACCOMMODATION"
            ]
        },
        "uri": {
            "$id": "#/properties/uri",
            "type": "string",
            "title": "The uri schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "http://localhost:8080/products/43dcecc9-724c-4062-ac8f-402621f18485"
            ]
        },
        "supplierId": {
            "$id": "#/properties/supplierId",
            "type": "string",
            "title": "The supplierId schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "cd96b919-d54d-43ca-b648-b90153def1b2"
            ]
        },
        "_class": {
            "$id": "#/properties/_class",
            "type": "string",
            "title": "The _class schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "com.omega.bioway.ProductSearch.crosscutting.entities.Product"
            ]
        }
    },
    "additionalProperties": true
}

=== MSCloud2130/Bioway/TestData/ProductSearch/soap-product.json
[
  {
    "_id": "43dcecc9-724c-4062-ac8f-402621f18485",
    "name": "Hotel Santa Marta",
    "type": "ACCOMMODATION",
    "uri": "http://localhost:8080/products/43dcecc9-724c-4062-ac8f-402621f18485",
    "supplierId": "cd96b919-d54d-43ca-b648-b90153def1b2",
    "_class": "com.omega.bioway.ProductSearch.crosscutting.entities.Product"
  },
  {
    "_id": "227e4e0d-320e-491e-9258-15b100a7ed08",
    "name": "Tour Parque Tayrona",
    "type": "ECOTOUR",
    "uri": "http://localhost:8080/products/227e4e0d-320e-491e-9258-15b100a7ed08",
    "supplierId": "cd96b919-d54d-43ca-b648-b90153def1b2",
    "_class": "com.omega.bioway.ProductSearch.crosscutting.entities.Product"
  }
]

=== MSCloud2130/Bioway/Diseño/Persistencia/ProductSearch/cart_example.json
{
    "_id": "43dcecc9-724c-4062-ac8f-402621f18485",
    "name": "Hotel Santa Marta",
    "type": "ACCOMMODATION",
    "uri": "http://localhost:8080/products/43dcecc9-724c-4062-ac8f-402621f18485",
    "supplierId": "cd96b919-d54d-43ca-b648-b90153def1b2",
    "_class": "com.omega.bioway.ProductSearch.crosscutting.entities.Product"
 }
