=== MSCloud2130/Bioway/Diseño/Persistencia/cart/cart_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The root schema",
    "description": "Schema usado para la persistencia de los productos en el microservicio cart",
    "default": {},
    "examples": [
        {
            "_id": "91a5c64c-f34e-491a-bb40-55c4a0563d6b",
            "totalCost": 1000,
            "items": [
                {
                    "productId": "43dcecc9-724c-4062-ac8f-402621f18485",
                    "productUrl": "http://localhost:8080/products/43dcecc9-724c-4062-ac8f-402621f18485",
                    "quantity": 2,
                    "unitPrice": 500
                }
            ],
            "_class": "com.omega.bioway.cart.crosscutting.entities.Cart"
        }
    ],
    "required": [
        "_id",
        "totalCost",
        "items",
        "_class"
    ],
    "properties": {
        "_id": {
            "$id": "#/properties/_id",
            "type": "string",
            "title": "The _id schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "91a5c64c-f34e-491a-bb40-55c4a0563d6b"
            ]
        },
        "totalCost": {
            "$id": "#/properties/totalCost",
            "type": "integer",
            "title": "The totalCost schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                1000
            ]
        },
        "items": {
            "$id": "#/properties/items",
            "type": "array",
            "title": "The items schema",
            "description": "An explanation about the purpose of this instance.",
            "default": [],
            "examples": [
                [
                    {
                        "productId": "43dcecc9-724c-4062-ac8f-402621f18485",
                        "productUrl": "http://localhost:8080/products/43dcecc9-724c-4062-ac8f-402621f18485",
                        "quantity": 2,
                        "unitPrice": 500
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/items/items",
                "anyOf": [
                    {
                        "$id": "#/properties/items/items/anyOf/0",
                        "type": "object",
                        "title": "The first anyOf schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": {},
                        "examples": [
                            {
                                "productId": "43dcecc9-724c-4062-ac8f-402621f18485",
                                "productUrl": "http://localhost:8080/products/43dcecc9-724c-4062-ac8f-402621f18485",
                                "quantity": 2,
                                "unitPrice": 500
                            }
                        ],
                        "required": [
                            "productId",
                            "productUrl",
                            "quantity",
                            "unitPrice"
                        ],
                        "properties": {
                            "productId": {
                                "$id": "#/properties/items/items/anyOf/0/properties/productId",
                                "type": "string",
                                "title": "The productId schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "43dcecc9-724c-4062-ac8f-402621f18485"
                                ]
                            },
                            "productUrl": {
                                "$id": "#/properties/items/items/anyOf/0/properties/productUrl",
                                "type": "string",
                                "title": "The productUrl schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "http://localhost:8080/products/43dcecc9-724c-4062-ac8f-402621f18485"
                                ]
                            },
                            "quantity": {
                                "$id": "#/properties/items/items/anyOf/0/properties/quantity",
                                "type": "integer",
                                "title": "The quantity schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    2
                                ]
                            },
                            "unitPrice": {
                                "$id": "#/properties/items/items/anyOf/0/properties/unitPrice",
                                "type": "integer",
                                "title": "The unitPrice schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": 0,
                                "examples": [
                                    500
                                ]
                            }
                        },
                        "additionalProperties": true
                    }
                ]
            }
        },
        "_class": {
            "$id": "#/properties/_class",
            "type": "string",
            "title": "The _class schema",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
                "com.omega.bioway.cart.crosscutting.entities.Cart"
            ]
        }
    },
    "additionalProperties": true
}

=== MSCloud2130/Bioway/Diseño/Persistencia/cart/cart_example.json
{
    "_id": "91a5c64c-f34e-491a-bb40-55c4a0563d6b",
    "totalCost": 1000,
    "items": [
      {
        "productId": "43dcecc9-724c-4062-ac8f-402621f18485",
        "productUrl": "http://localhost:8080/products/43dcecc9-724c-4062-ac8f-402621f18485",
        "quantity": 2,
        "unitPrice": 500
      }
    ],
    "_class": "com.omega.bioway.cart.crosscutting.entities.Cart"
}
